version: "3.9"
services:
  php81:
    build:
      context: docker/php81
    working_dir: /app
    volumes:
      - .:/app:${MOUNT_TYPE:-delegated}

  php74:
    build:
      context: docker/php74
    working_dir: /app
    volumes:
      - .:/app:${MOUNT_TYPE:-delegated}

  php71:
    build:
      context: docker/php71
    working_dir: /app
    volumes:
      - .:/app:${MOUNT_TYPE:-delegated}
