services:
  php82:
    volumes:
      - app:/app

  php74:
    volumes:
      - app:/app

  php71:
    volumes:
      - app:/app

volumes:
  app:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: false
    app:
      alpha: "."
      beta: "volume://app"
