services:
  php:
    volumes:
      - app:/app

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

volumes:
  app:

x-mutagen:
  sync:
    defaults:
      mode: "two-way-resolve"
      ignore:
        vcs: false
    app:
      alpha: "."
      beta: "volume://app"
